image: Visual Studio 2017

platform: x64

cache:
  - c:\miktex -> appveyor.yml

environment:
  global:
    USE_ATLAS: YES
    ATLAS_PATH: C:/projects/r-openblas/libopenBLAS
    MULTI: 64
    WIN: 64
    BINPREF64: c:/Rtools/mingw_64/bin/
    TEXI2DVI: TEXINDEX=C:/Rtools/bin/texindex.exe texify
    TEXI2ANY: C:/Perl/bin/perl.exe -IC:/msys64/usr/bin C:/msys64/usr/bin/texi2any
    ISDIR: C:/Program Files (x86)/Inno Setup 5
    # QPDF: C:/qpdf
    TMPDIR: C:/Users/appveyor/AppData/Local/Temp
    CPATH: ../../extsoft/include
    EOPTS: -mtune=haswell

install:
  # Install miktex to get pdflatex, if we don't get it from the cache
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe appveyor DownloadFile http://mirror.utexas.edu/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable.exe
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe 7z x miktex-portable.exe -oC:\miktex >NUL
  - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin;"
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  - initexmf --set-config-value "[MPM]AutoInstall=1"
  - git submodule update --init --recursive
  - ps: Import-Module '.\scripts\appveyor-tool.ps1'
  - ps: Bootstrap
  - cp -r c:\Rtools\Tcl64 r-source\Tcl

build_script:
  - ECHO %PATH%
  - cp src/extra/blas/Makefile.win r-source/src/extra/blas/.

  - gcc --version
  - gfortran --version

  - cd r-source/src/gnuwin32
  - make rsync-recommended
  - make rsync-extsoft
  - make all
  - make distribution

artifacts:
  - path: r-source/src/gnuwin32/installer/R*-win*.exe

deploy:
  release: ROpenBLAS-v$(appveyor_build_version)
  description: 'This is R, but compiled for windwos using OpenBLAS'
  provider: GitHub
  auth_token:
    secure: 6VduGFAfk0LDLzJDnzCakW7vldMxkkaw4OHCYkFqyecDV9sKE+MdEP5Go4zpmt3c
  artifact: r-source/src/gnuwin32/installer/R*-win*.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
